### ISSUE TITLE
Fix identation in the README snippet

### ISSUE THREAD

**Issue by LouisCAD** [AndroidDevFr/AndroidForm#1]
The identation should be 4 spaces, but the initial ident is 12 spaces. Also, the last curly brace is missing.

For reference, here's the [Android Kotlin Style guide](https://android.github.io/kotlin-guides/style.html) and [here's a DSL example from Kotlin doc](https://kotlinlang.org/docs/reference/type-safe-builders.html)

**Comment by florent37** [comment]
can you make a pull request to fix it ?

**Comment by florent37** [comment]
done #2
